/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exURI1002;
/*
 * @author moyses
 * 
 */
public class Circulo {
    private double raio;
    private static final double PI = 3.14159;
	
    public Circulo(double raio) {
		super();
		this.raio = raio;
	}
   
    public double getArea() {
    	return raio*raio* PI;
    }
}
